export const ERROR_CODES = {  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_VERIFICATION_FAILED: 'TOKEN_VERIFICATION_FAILED',
  REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',

  // User Related
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Database
  DATABASE_ERROR: 'DATABASE_ERROR',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // Server
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  // File & Upload
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // Contest & Award Related
  CONTEST_NOT_FOUND: 'CONTEST_NOT_FOUND',
  CONTESTANT_NOT_FOUND: 'CONTESTANT_NOT_FOUND',
  AWARD_NOT_FOUND: 'AWARD_NOT_FOUND',
  AWARD_TYPE_EXISTS: 'AWARD_TYPE_EXISTS',
} as const;

export const ERROR_MESSAGES = {  [ERROR_CODES.UNAUTHORIZED]: 'Unauthorized access',
  [ERROR_CODES.FORBIDDEN]: 'Access forbidden',
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid credentials',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Token has expired',
  [ERROR_CODES.INVALID_TOKEN]: 'Invalid token',
  [ERROR_CODES.TOKEN_VERIFICATION_FAILED]: 'Token verification failed',
  [ERROR_CODES.REFRESH_TOKEN_REQUIRED]: 'Refresh token is required',
  [ERROR_CODES.ACCOUNT_DEACTIVATED]: 'Account is deactivated',

  [ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [ERROR_CODES.USER_ALREADY_EXISTS]: 'User already exists',
  [ERROR_CODES.EMAIL_ALREADY_EXISTS]: 'Email already exists',
  [ERROR_CODES.USERNAME_ALREADY_EXISTS]: 'Username already exists',

  [ERROR_CODES.VALIDATION_ERROR]: 'Validation error',
  [ERROR_CODES.INVALID_INPUT]: 'Invalid input',
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 'Missing required field',

  [ERROR_CODES.DATABASE_ERROR]: 'Database error',
  [ERROR_CODES.RECORD_NOT_FOUND]: 'Record not found',
  [ERROR_CODES.DUPLICATE_ENTRY]: 'Duplicate entry',

  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service unavailable',
  [ERROR_CODES.NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.METHOD_NOT_ALLOWED]: 'Method not allowed',
  [ERROR_CODES.TOO_MANY_REQUESTS]: 'Too many requests',
  [ERROR_CODES.FILE_TOO_LARGE]: 'File too large',
  [ERROR_CODES.INVALID_FILE_TYPE]: 'Invalid file type',
  [ERROR_CODES.UPLOAD_FAILED]: 'Upload failed',

  [ERROR_CODES.CONTEST_NOT_FOUND]: 'Contest not found',
  [ERROR_CODES.CONTESTANT_NOT_FOUND]: 'Contestant not found',
  [ERROR_CODES.AWARD_NOT_FOUND]: 'Award not found',
  [ERROR_CODES.AWARD_TYPE_EXISTS]: 'Award type already exists',
} as const;
